
-- Add new workflow fields to costing_configs
ALTER TABLE public.costing_configs
  ADD COLUMN IF NOT EXISTS channel text NOT NULL DEFAULT 'Retail',
  ADD COLUMN IF NOT EXISTS sides text NOT NULL DEFAULT 'Single Side',
  ADD COLUMN IF NOT EXISTS box_type text NOT NULL DEFAULT 'With Box',
  ADD COLUMN IF NOT EXISTS pack_type text NOT NULL DEFAULT 'Roll Pack',
  ADD COLUMN IF NOT EXISTS model text NOT NULL DEFAULT 'Normal',
  ADD COLUMN IF NOT EXISTS thickness_in numeric NOT NULL DEFAULT 6,
  ADD COLUMN IF NOT EXISTS spring_wire text NOT NULL DEFAULT '1.8mm Grade II',
  ADD COLUMN IF NOT EXISTS spring_turns integer NOT NULL DEFAULT 5,
  ADD COLUMN IF NOT EXISTS spring_count integer NOT NULL DEFAULT 420,
  ADD COLUMN IF NOT EXISTS spring_weight_kg numeric NOT NULL DEFAULT 9.45,
  ADD COLUMN IF NOT EXISTS spiral_wire_kg numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS border_wire_kg numeric NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS corner_spring_kg numeric NOT NULL DEFAULT 0.22,
  ADD COLUMN IF NOT EXISTS m_spring_kg numeric NOT NULL DEFAULT 0.44,
  ADD COLUMN IF NOT EXISTS cotton_felt_gsm integer NOT NULL DEFAULT 700,
  ADD COLUMN IF NOT EXISTS cotton_felt_kg numeric NOT NULL DEFAULT 2.44,
  ADD COLUMN IF NOT EXISTS comfort_foam text NOT NULL DEFAULT '18D PU Foam',
  ADD COLUMN IF NOT EXISTS comfort_foam_mm integer NOT NULL DEFAULT 10,
  ADD COLUMN IF NOT EXISTS comfort_foam_kg numeric NOT NULL DEFAULT 0.9,
  ADD COLUMN IF NOT EXISTS quilt_foam text NOT NULL DEFAULT '10D LD Foam',
  ADD COLUMN IF NOT EXISTS quilt_foam_mm integer NOT NULL DEFAULT 8,
  ADD COLUMN IF NOT EXISTS quilt_foam_kg numeric NOT NULL DEFAULT 0.16,
  ADD COLUMN IF NOT EXISTS rebonded_foam_mm integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS rebonded_foam_kg numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS memory_foam_mm integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS memory_foam_kg numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS sidewall_foam_type text NOT NULL DEFAULT 'None',
  ADD COLUMN IF NOT EXISTS sidewall_foam_kg numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS panel_fabric_mtr numeric NOT NULL DEFAULT 1.98,
  ADD COLUMN IF NOT EXISTS border_fabric_mtr numeric NOT NULL DEFAULT 0.5,
  ADD COLUMN IF NOT EXISTS tape_edge_mtr numeric NOT NULL DEFAULT 11.58,
  ADD COLUMN IF NOT EXISTS pvc_kg numeric NOT NULL DEFAULT 0.32,
  ADD COLUMN IF NOT EXISTS hdpe_kg numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS wastage_percent numeric NOT NULL DEFAULT 4;
